{
    "ID": {
        "GitHub_Advisory_Database": {
            "aliases": [
                "CVE-2019-19844"
            ]
        },
        "Nomisec1": {
            "id": 229376107,
            "name": "django_cve_2019_19844_poc",
            "full_name": "ryu22e/django_cve_2019_19844_poc"
        },
        "Nomisec2": {
            "id": 230083007,
            "name": "django_cve201919844",
            "full_name": "andripwn/django_cve201919844"
        },
        "Nomisec3": {
            "id": 234739158,
            "name": "CVE_2019_19844",
            "full_name": "0xsha/CVE_2019_19844"
        }
    },
    "summary": "Django Potential account hijack via password reset form",
    "details": {
        "GitHub_Advisory_Database": "Django before 1.11.27, 2.x before 2.2.9, and 3.x before 3.0.1 allows account takeover. A suitably crafted email address (that is equal to an existing user's email address after case transformation of Unicode characters) would allow an attacker to be sent a password reset token for the matched user account. (One mitigation in the new releases is to send password reset tokens only to the registered user email address.)"
    },
    "description": {
        "Nomisec1": "PoC for CVE-2019-19844(https://www.djangoproject.com/weblog/2019/dec/18/security-releases/)",
        "Nomisec2": "PoC for CVE-2019-19844 ( https://www.djangoproject.com/weblog/2019/dec/18/security-releases/ )",
        "Nomisec3": "CVE-2019-19844 Docker Edition"
    },
    "topics": [
        "2019",
        "releases",
        "email",
        "address",
        "reset",
        "www",
        "18",
        "account",
        "password",
        "com"
    ],
    "severity": [],
    "affected": [],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-19844"
        },
        {
            "type": "WEB",
            "url": "https://github.com/django/django/commit/302a4ff1e8b1c798aab97673909c7a3dfda42c26"
        },
        {
            "type": "WEB",
            "url": "https://github.com/django/django/commit/4d334bea06cac63dc1272abcec545b85136cca0e"
        },
        {
            "type": "WEB",
            "url": "https://github.com/django/django/commit/5b1fbcef7a8bec991ebe7b2a18b5d5a95d72cb70"
        },
        {
            "type": "WEB",
            "url": "https://github.com/django/django/commit/f4cff43bf921fcea6a29b726eb66767f67753fa2"
        },
        {
            "type": "PACKAGE",
            "url": "https://github.com/django/django"
        },
        {
            "type": "WEB",
            "url": "https://groups.google.com/forum/#!topic/django-announce/3oaB2rVH3a0"
        },
        {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HCM2DPUI7TOZWN4A6JFQFUVQ2XGE7GUD"
        },
        {
            "type": "WEB",
            "url": "https://seclists.org/bugtraq/2020/Jan/9"
        },
        {
            "type": "WEB",
            "url": "https://security.gentoo.org/glsa/202004-17"
        },
        {
            "type": "WEB",
            "url": "https://security.netapp.com/advisory/ntap-20200110-0003"
        },
        {
            "type": "WEB",
            "url": "https://usn.ubuntu.com/4224-1"
        },
        {
            "type": "WEB",
            "url": "https://www.debian.org/security/2020/dsa-4598"
        },
        {
            "type": "WEB",
            "url": "https://www.djangoproject.com/weblog/2019/dec/18/security-releases"
        },
        {
            "type": "WEB",
            "url": "http://packetstormsecurity.com/files/155872/Django-Account-Hijack.html"
        }
    ],
    "proof_of_concept": {
        "owner1": {
            "html_url": "https://github.com/ryu22e"
        },
        "html_url1": "https://github.com/ryu22e/django_cve_2019_19844_poc",
        "owner2": {
            "html_url": "https://github.com/andripwn"
        },
        "html_url2": "https://github.com/andripwn/django_cve201919844",
        "owner3": {
            "html_url": "https://github.com/0xsha"
        },
        "html_url3": "https://github.com/0xsha/CVE_2019_19844"
    },
    "has_discussions": null,
    "database_specific": {
        "cwe_ids": [
            "CWE-640"
        ],
        "severity": "CRITICAL",
        "github_reviewed": true,
        "github_reviewed_at": "2020-01-16T22:34:58Z",
        "nvd_published_at": null
    },
    "Time_Description": {
        "GitHub_Advisory_Database": {
            "modified": "2023-09-05T13:59:29Z",
            "published": "2020-01-16T22:35:12Z",
            "withdrawn": null
        },
        "Nomisec": {
            "created_at1": "2019-12-21T04:30:34Z",
            "updated_at1": "2024-08-30T17:23:17Z",
            "pushed_at1": "2019-12-24T12:31:47Z",
            "created_at2": "2019-12-25T10:05:48Z",
            "updated_at2": "2024-08-12T19:56:01Z",
            "pushed_at2": "2020-09-20T16:23:45Z",
            "created_at3": "2020-01-18T13:32:21Z",
            "updated_at3": "2024-08-12T19:56:46Z",
            "pushed_at3": "2021-09-22T18:25:53Z"
        }
    }
}