{
    "ID": {
        "GitHub_Advisory_Database": {
            "aliases": [
                "CVE-2021-21978"
            ]
        },
        "Nomisec1": {
            "id": 344688633,
            "name": "CVE-2021-21978",
            "full_name": "GreyOrder/CVE-2021-21978"
        },
        "Nomisec2": {
            "id": 344694759,
            "name": "CVE-2021-21978",
            "full_name": "me1ons/CVE-2021-21978"
        },
        "Nomisec3": {
            "id": 344740961,
            "name": "CVE-2021-21978",
            "full_name": "skytina/CVE-2021-21978"
        }
    },
    "summary": null,
    "details": {
        "GitHub_Advisory_Database": "VMware View Planner 4.x prior to 4.6 Security Patch 1 contains a remote code execution vulnerability. Improper input validation and lack of authorization leading to arbitrary file upload in logupload web application. An unauthorized attacker with network access to View Planner Harness could upload and execute a specially crafted file leading to remote code execution within the logupload container."
    },
    "description": {
        "Nomisec1": "CVE-2021-21978 exp",
        "Nomisec2": "CVE-2021-21978 EXP",
        "Nomisec3": "带回显版本的漏洞利用脚本"
    },
    "topics": [
        "view",
        "exp",
        "leading",
        "upload",
        "2021",
        "vmware",
        "file",
        "container",
        "authorization",
        "lack"
    ],
    "severity": [],
    "affected": [],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-21978"
        },
        {
            "type": "WEB",
            "url": "https://www.vmware.com/security/advisories/VMSA-2021-0003.html"
        },
        {
            "type": "WEB",
            "url": "http://packetstormsecurity.com/files/161879/VMware-View-Planner-4.6-Remote-Code-Execution.html"
        }
    ],
    "proof_of_concept": {
        "owner1": {
            "html_url": "https://github.com/GreyOrder"
        },
        "html_url1": "https://github.com/GreyOrder/CVE-2021-21978",
        "owner2": {
            "html_url": "https://github.com/me1ons"
        },
        "html_url2": "https://github.com/me1ons/CVE-2021-21978",
        "owner3": {
            "html_url": "https://github.com/skytina"
        },
        "html_url3": "https://github.com/skytina/CVE-2021-21978"
    },
    "has_discussions": null,
    "database_specific": {
        "cwe_ids": [
            "CWE-434"
        ],
        "severity": "CRITICAL",
        "github_reviewed": false,
        "github_reviewed_at": null,
        "nvd_published_at": "2021-03-03T18:15:00Z"
    },
    "Time_Description": {
        "GitHub_Advisory_Database": {
            "modified": "2023-08-08T15:31:16Z",
            "published": "2022-05-24T17:43:32Z",
            "withdrawn": null
        },
        "Nomisec": {
            "created_at1": "2021-03-05T03:58:33Z",
            "updated_at1": "2024-10-03T05:15:22Z",
            "pushed_at1": "2021-03-05T04:22:26Z",
            "created_at2": "2021-03-05T04:33:19Z",
            "updated_at2": "2024-08-12T20:10:55Z",
            "pushed_at2": "2021-03-05T04:42:17Z",
            "created_at3": "2021-03-05T08:15:27Z",
            "updated_at3": "2024-08-12T20:10:55Z",
            "pushed_at3": "2021-03-05T11:09:06Z"
        }
    }
}